# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '\u6587\u7ae0'},
        ),
    ]
