# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160504_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=10000, verbose_name='\u5185\u5bb9'),
        ),
    ]
