# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_auto_20160421_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name_plural': '\u7248\u5757'},
        ),
    ]
